name: GitHub Actions Demo
on:
 push:
   branches: [main]
   paths-ignore: 
    '.github/**' 

 pull_request:
      branches: [main]
    
 schedule:
   - cron: "15 6 * * 0"
     
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
        
      - name: Display Triggering Event
        run: echo "The triggering event was ${{ github.event_name }}"
        
      - name: Display Current Branch
        run: echo "The repository is currently referencing the branch: ${{ github.ref }}"

      - name: List All Files
        run: |
          echo "Listing all files in the repository:"
          find . -type f

        
      

 

  
